version: '3'
services:
vpronginx:
    image: visualpath/vpronginx
    ports:
      - "80:80"
  vproapp:
    image: imranvisualpath/vproappfix
    ports:
      - "8080:8080"
  vprodb:
    image: imranvisualpath/vprdbfix
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

